### ISSUE TITLE
DB sizes doesnt add up

### ISSUE THREAD

**Issue by MaBeniu** [jehy/hass-addons#10]
Hi I find this super helpful addon, easy to use and easy to find the problems.
the only thing I suspect something is not taken into consideration.
If I look at the database size via file manager its size is approx. 350MB however when i look with this addon approx total sum size is around 160MB. So I wonder where is the gap of 190MB more than half isnt shown...??

DB size in file manager:
![image](https://github.com/user-attachments/assets/40258d70-b130-462c-99a6-810c3cda4440)
DB tables sizes in the DbStats:
![image](https://github.com/user-attachments/assets/99e15335-ffa6-497c-a784-e374882254ce)
Or it is not suppose to show full view of sizes??

**Comment by jehy** [comment]
Hi! Table size is taken from database special metadata tables, so it quite correct.

But database size file size can't be equal to the sum of table sizes, since there are indexes, caches, redo logs, system tables and many other things, specific for each database type.

Also, database often does not shrink size after data deletion unless you run `vacuum` command.
So it's perfectly fine even if empty database [takes up 70 MB space :)](https://stackoverflow.com/questions/4438394/an-empty-sqlite-database-takes-74-mb)
